/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ooop;

import ooop.analysis.LetterFrequencyAnalysis;

public class App {

    public static void main(String[] args) {
        new LetterFrequencyAnalysis().launch(args);
    }
}
